### ISSUE TITLE
declension of mahat

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-inflect#2]
Code addition for declensions of *mahat* and its compounds.

The declensions in m. and n. genders are mostly like those of adjectives ending in '-mat' or '-vat' (such as *DImat*)
but with a 'strong' form ('A' instead of 'a') in some numbers of the nominative, accusative, and vocative cases.
References: Kale Higher Sanskrit Grammar, p. 71, and Deshpande Sanskrit Primer, p. 191.

Declension of m_vat mahat

|Case|S|D|P|
|-|-|-|-|
|Nominative|mahAn|mahAntO|mahAntaH|
|Accusative|mahAntam|mahAntO|mahataH|
|Instrumental|mahatA|mahadByAm|mahadBiH|
|Dative|mahate|mahadByAm|mahadByaH|
|Ablative|mahataH|mahadByAm|mahadByaH|
|Genitive|mahataH|mahatoH|mahatAm|
|Locative|mahati|mahatoH|mahatsu|
|Vocative|mahan|mahAntO|mahAntaH|

Declension of n_vat mahat

|Case|S|D|P|
|-|-|-|-|
|Nominative|mahat|mahatI|mahAnti|
|Accusative|mahat|mahatI|mahAnti|
|Instrumental|mahatA|mahadByAm|mahadBiH|
|Dative|mahate|mahadByAm|mahadByaH|
|Ablative|mahataH|mahadByAm|mahadByaH|
|Genitive|mahataH|mahatoH|mahatAm|
|Locative|mahati|mahatoH|mahatsu|
|Vocative|mahat|mahatI|mahAnti|

**Comment by funderburkjim** [comment]
## DImat for comparison

Declension of m_vat DImat

|Case|S|D|P|
|-|-|-|-|
|Nominative|DImAn|DImantO|DImantaH|
|Accusative|DImantam|DImantO|DImataH|
|Instrumental|DImatA|DImadByAm|DImadBiH|
|Dative|DImate|DImadByAm|DImadByaH|
|Ablative|DImataH|DImadByAm|DImadByaH|
|Genitive|DImataH|DImatoH|DImatAm|
|Locative|DImati|DImatoH|DImatsu|
|Vocative|DIman|DImantO|DImantaH|

Declension of n_vat DImat

|Case|S|D|P|
|-|-|-|-|
|Nominative|DImat|DImatI|DImanti|
|Accusative|DImat|DImatI|DImanti|
|Instrumental|DImatA|DImadByAm|DImadBiH|
|Dative|DImate|DImadByAm|DImadByaH|
|Ablative|DImataH|DImadByAm|DImadByaH|
|Genitive|DImataH|DImatoH|DImatAm|
|Locative|DImati|DImatoH|DImatsu|
|Vocative|DImat|DImatI|DImanti|

**Comment by drdhaval2785** [comment]
closable?

**Comment by funderburkjim** [comment]
Yes. Proof:

![image](https://user-images.githubusercontent.com/6393033/102023406-59ed3180-3d5a-11eb-89fd-7204d1498d21.png)
