### ISSUE TITLE
Huet aorist forms

### ISSUE THREAD

**Issue by funderburkjim** [sanskrit-lexicon/csl-inflect#4]
Currently, only the aorist forms from Deshpande's text are available in this repository and its 
associated display:

![image](https://user-images.githubusercontent.com/6393033/79786631-c28f2600-8313-11ea-9026-1703c631f4fe.png)

This issue documents the steps in incorporating the aorist forms published by Gerard Huet.
The starting point for this is the `huet_conj_tables_aor.txt` file in https://github.com/sanskrit-lexicon/csl-inflect/tree/master/huetdata.

**Comment by gasyoun** [comment]
> incorporating the aorist forms published by Gerard Huet

It means dhatu review has come to a logical end untill we do not find the missing parts, right?

**Comment by funderburkjim** [comment]
Maybe will do the dhatu review for GRA , BEN.  Worth doing?

But first wanted to get the aorist forms into the inflection display.

**Comment by gasyoun** [comment]
> But first wanted to get the aorist forms into the inflection display.

Understood.

> Maybe will do the dhatu review for GRA , BEN. Worth doing?

Sure, answered in yesterday's topic. GRA I use almost everyday. BEN not so, but it sure deserves some attention.

**Comment by funderburkjim** [comment]
## Huet roots with aorist forms.

There are 355 tables of aorist forms in the Huet data.  
These involve 132 distinct roots.
[verb_cp_huet_aor.txt](https://github.com/sanskrit-lexicon/csl-inflect/blob/master/verbs/pysanskritv2/inputs/verb_cp_huet_aor.txt) show the associated MW root
records.

## Mapping to MW verb records

9 of the 132 roots are spelled differently by Huet and MW.  
```
; Huet spelling DyA -> MW spelling DyE
; Huet spelling praS -> MW spelling praC
; Huet spelling mUrC -> MW spelling murC
; Huet spelling mlecC -> MW spelling mleC
; Huet spelling vyA -> MW spelling vye
; Huet spelling SA -> MW spelling Si
; Huet spelling SU -> MW spelling Svi
; Huet spelling sA -> MW spelling so
; Huet spelling hU -> MW spelling hve
```
The mapping was determined by comparing Huet's Heritage dictionary entries with MW entries.
For example, hU in the Huet dictionary:
![image](https://user-images.githubusercontent.com/6393033/79802364-d3e52c00-832d-11ea-94c3-5f96f6f45a83.png)

In MW,  'hU' : ←  (H1) [p= 1301,3] :  1. hū weak form of √hve, p.1308. [ID=263601]
and 'hve':
![image](https://user-images.githubusercontent.com/6393033/79802509-127ae680-832e-11ea-814d-fc7e9a91bba2.png)

## some 'non-genuine' roots 
Most of the csl-inflect work with verbs is restricted to the verbs which MW marks as 'genuine'.
12 of the verbs for which Huet has aorist inflections are verbs which MW marks as non-genuine.
While we aim to make the aorist forms of these verbs accessible to the display,  we currently
defer attempting to compute other inflections (present, etc.) of these.  If and when the need
arises, we can add the present forms of these verbs (in particular, add them to 
the verbs inlist [verb_cp.txt](https://github.com/sanskrit-lexicon/csl-inflect/blob/master/verbs/pysanskritv2/inputs/verb_cp.txt) which have present and other inflections.

**Comment by gasyoun** [comment]
> 12 of the verbs for which Huet has aorist inflections are verbs which MW marks as non-genuine.

So in a century from now the genuity could be revised, interesting.

**Comment by funderburkjim** [comment]
## aorist forms now added

All the aorist forms from Huet's DATA/XML have now been added.
Example from display, for 'AsTat':
Previously, from Deshpande:
![image](https://user-images.githubusercontent.com/6393033/80256882-aeb62d80-864d-11ea-9906-e6bbf75336f6.png)

Current, Including Huet data:

![image](https://user-images.githubusercontent.com/6393033/80256922-c4c3ee00-864d-11ea-81e8-de859e443044.png)


Note previously, Deshpande data included forms from 'BU'  also under 'as'.  I changed 'aBUt', etc.
to be associated with BU only:

![image](https://user-images.githubusercontent.com/6393033/80257026-02287b80-864e-11ea-919a-f2b2ede036e0.png)

**Comment by funderburkjim** [comment]
## Integration of Huet and Deshpande forms

This proved more difficult than expected.
* There is some overlap and some difference in the verbs with aorist forms from these two sources.
   * 252 partial or complete (usual) aorist (active or middle voice) conjugation tables from Huet 
   * 232 partial (usual) or complete aorist (active or middle voice) conjugation tables from Deshpande
* When a given verb/voice appears in conjugation tables from both, sometimes the common forms
   agree and sometimes they don't. 
  * [merge_tables_aorist_log.txt](https://github.com/sanskrit-lexicon/csl-inflect/blob/master/verbs/pysanskritv2/manual/aor/merge_tables_aorist_log.txt#L1177) provides
   some details regarding how the data from the two sources was merged.
* for aorist passive forms,  both Huet and Deshpande provide only 3rd person singular forms.
  For roots appearing in both sources, the given forms agree except in 2 cases. See
  [merge_tables_aorist_passive_log.txt](https://github.com/sanskrit-lexicon/csl-inflect/blob/master/verbs/pysanskritv2/manual/aor/merge_tables_aorist_passive_log.txt).

## algorithmic and manual forms
The other source of difficulty relates to the fact that, for verb forms in general,  there needs to
be the ability to handle both:
* algorithmically generated forms.  There is reliable Python code for generating conjugation
  tables for the present family of tenses (present, imperfect, optative, imperative) in active, middle,
  and passive voices FOR verbs of conjugation classes 1, 4, 6, 10.  There are also algorithms for
  some other tenses (but I'm not sure exactly which at the moment).
* But for many other forms (such as present tense forms for classes, 2, 3, 5, 7, 8, 9), the algorithms
  are less reliable, so I have chosen to use *manual* conjugation tables -- mainly tables digitized
  from Deshpande's text.

For the aorist,  this is the first batch of verb forms from a source other than Deshpande.
   Some progress was made that should allow greater ease in
   incorporating additional forms from Huet's published data.

**Comment by gasyoun** [comment]
> There is reliable Python code for generating conjugation tables

And it can be found ...?

>classes, 2, 3, 5, 7, 8, 9), the algorithms are less reliable, so I have chosen to use manual conjugation tables

Understood.

**Comment by funderburkjim** [comment]
## aorist forms installed

The aorist forms from Huet have been merged with those from Deshpande, and the result installed.

The installed conjugation tables are now in [tables_aorist.txt](https://github.com/sanskrit-lexicon/csl-inflect/blob/master/verbs/pysanskritv2/manual/tables_aorist.txt) for active and middle
voices, and [tables_aorist_passive.txt](https://github.com/sanskrit-lexicon/csl-inflect/blob/master/verbs/pysanskritv2/manual/tables_aorist_passive.txt) for passive voice.

**Comment by gasyoun** [comment]
> Huet have been merged with those from Deshpande

Good news. Hope Huet reviews some of the forms after as well, if needed.

**Comment by drdhaval2785** [comment]
Closable?

**Comment by funderburkjim** [comment]
Yes, closable
